# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080